conky.config = {
    alignment = 'top_left',

    background = true,
    double_buffer = true,

    own_window = true,
    own_window_type = 'desktop',
    own_window_class = 'NED-OS-HUD',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    border_width = 0,
    draw_borders = false,
    draw_outline = false,
    draw_shades = false,

    use_xft = true,
    font = 'JetBrains Mono:size=9',
    xftalpha = 1.0,

    default_color = '#d0d0d0',

    gap_x = 45,
    gap_y = 75,

    minimum_width = 300,
    minimum_height = 150,

    update_interval = 2,
    cpu_avg_samples = 2,

    own_window_argb_visual = true,
    own_window_argb_value = 0,
};

conky.text = [[
${font JetBrains Mono:bold:size=10}${color #f2f2f2}SYSTEM STATUS${color}${font}
${hr 1}
CPU       ${cpu cpu0}%
RAM       ${memperc}%
DISK      ${fs_used_perc /}%
NET       ${downspeed wlo1}/s
UPTIME    ${uptime_short}
]];
